name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Upload file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - API Server
        - Web Dashboard
        - CLI
        - COBOL Parser
        - Fortran Parser
        - VB6 Parser
        - Java Legacy Parser
        - Archeologist Agent
        - Architect Agent
        - Builder Agent
        - Validator Agent
        - Database
        - Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: source-language
    attributes:
      label: Source Language (if applicable)
      description: Which legacy language were you migrating?
      options:
        - Not applicable
        - COBOL
        - Fortran
        - Visual Basic 6
        - VBA
        - Legacy Java (J2EE/EJB)

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14.0]
        - Node.js version: [e.g., 20.10.0]
        - MigrationPilot version: [e.g., 0.1.0]
        - Deployment: [e.g., Docker, Kubernetes, Local]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      render: shell

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: text

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have read the documentation
          required: true
