/**
 * HTML Exporter
 * 
 * Exports documents to HTML format with optional styling
 */

import type { Document, DocumentSection, ExportOptions, ExportResult } from '../types.js';

export class HTMLExporter {
  /**
   * Export document to HTML string
   */
  export(document: Document, options?: ExportOptions): ExportResult {
    try {
      const content = this.renderDocument(document, options);
      
      return {
        success: true,
        format: 'html',
        content,
        size: content.length,
      };
    } catch (error) {
      return {
        success: false,
        format: 'html',
        error: error instanceof Error ? error.message : 'Unknown error',
      };
    }
  }

  private renderDocument(document: Document, options?: ExportOptions): string {
    const theme = options?.theme || 'light';
    const css = options?.customCss || this.getDefaultCSS(theme);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(document.title)}</title>
  <style>${css}</style>
</head>
<body>
  <div class="container">
    ${this.renderHeader(document, options)}
    ${options?.includeToc !== false ? this.renderTableOfContents(document.sections, options?.tocDepth || 3) : ''}
    <main class="content">
      ${document.sections.map(s => this.renderSection(s, options)).join('\n')}
    </main>
    ${this.renderFooter(document)}
  </div>
</body>
</html>`;
  }

  private renderHeader(document: Document, options?: ExportOptions): string {
    const logo = options?.logoUrl 
      ? `<img src="${this.escapeHtml(options.logoUrl)}" alt="Logo" class="logo">` 
      : '';

    return `
    <header class="document-header">
      ${logo}
      <h1>${this.escapeHtml(document.title)}</h1>
      <div class="metadata">
        <span class="badge">Version ${document.version}</span>
        <span class="badge confidence">${(document.confidenceScore * 100).toFixed(1)}% Confidence</span>
        <span class="badge">Generated: ${document.generatedAt.toLocaleDateString()}</span>
      </div>
    </header>`;
  }

  private renderTableOfContents(sections: DocumentSection[], maxDepth: number): string {
    const renderItems = (secs: DocumentSection[], depth: number): string => {
      if (depth > maxDepth) return '';
      
      return `<ul>
        ${secs.map(section => {
          const anchor = this.slugify(section.title);
          const children = section.subsections && depth < maxDepth
            ? renderItems(section.subsections, depth + 1)
            : '';
          return `<li><a href="#${anchor}">${this.escapeHtml(section.title)}</a>${children}</li>`;
        }).join('\n')}
      </ul>`;
    };

    return `
    <nav class="table-of-contents">
      <h2>Table of Contents</h2>
      ${renderItems(sections, 1)}
    </nav>`;
  }

  private renderSection(section: DocumentSection, options?: ExportOptions): string {
    const anchor = this.slugify(section.title);
    const level = Math.min(section.level + 1, 6);

    const confidenceIndicator = section.aiGenerated && section.confidence !== undefined
      ? `<span class="confidence-badge ${this.getConfidenceClass(section.confidence)}">${(section.confidence * 100).toFixed(0)}% AI confidence</span>`
      : '';

    const content = this.markdownToHtml(section.content || '');

    const sourceRefs = section.sourceReferences && section.sourceReferences.length > 0
      ? `<details class="source-references">
          <summary>Source References (${section.sourceReferences.length})</summary>
          <ul>
            ${section.sourceReferences.map(ref => 
              `<li>${this.escapeHtml(ref.name)}${ref.location ? ` (${ref.location.file}:${ref.location.startLine}-${ref.location.endLine})` : ''}</li>`
            ).join('\n')}
          </ul>
        </details>`
      : '';

    const subsections = section.subsections
      ? section.subsections.map(s => this.renderSection(s, options)).join('\n')
      : '';

    return `
    <section id="${anchor}" class="document-section level-${section.level}">
      <h${level}>${this.escapeHtml(section.title)} ${confidenceIndicator}</h${level}>
      <div class="section-content">${content}</div>
      ${sourceRefs}
      ${subsections}
    </section>`;
  }

  private renderFooter(document: Document): string {
    return `
    <footer class="document-footer">
      <p>Generated by MigrationPilot</p>
      <p>Completeness: ${(document.completeness * 100).toFixed(1)}%</p>
    </footer>`;
  }

  private markdownToHtml(markdown: string): string {
    // Simple markdown to HTML conversion
    let html = markdown;

    // Code blocks
    html = html.replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code class="language-$1">$2</code></pre>');
    
    // Inline code
    html = html.replace(/`([^`]+)`/g, '<code>$1</code>');
    
    // Tables
    html = this.convertTables(html);
    
    // Bold
    html = html.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    
    // Italic
    html = html.replace(/\*([^*]+)\*/g, '<em>$1</em>');
    
    // Links
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
    
    // Headers (within content)
    html = html.replace(/^### (.+)$/gm, '<h4>$1</h4>');
    html = html.replace(/^## (.+)$/gm, '<h3>$1</h3>');
    
    // Lists
    html = html.replace(/^- (.+)$/gm, '<li>$1</li>');
    html = html.replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>');
    
    // Blockquotes
    html = html.replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>');
    
    // Paragraphs
    html = html.replace(/\n\n/g, '</p><p>');
    html = `<p>${html}</p>`;
    
    // Clean up empty paragraphs
    html = html.replace(/<p>\s*<\/p>/g, '');
    
    return html;
  }

  private convertTables(markdown: string): string {
    const tableRegex = /\|(.+)\|\n\|[-| ]+\|\n((?:\|.+\|\n?)+)/g;
    
    return markdown.replace(tableRegex, (_match, header, body) => {
      const headers = header.split('|').filter((c: string) => c.trim()).map((c: string) => `<th>${c.trim()}</th>`).join('');
      const rows = body.trim().split('\n').map((row: string) => {
        const cells = row.split('|').filter((c: string) => c.trim()).map((c: string) => `<td>${c.trim()}</td>`).join('');
        return `<tr>${cells}</tr>`;
      }).join('\n');
      
      return `<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>`;
    });
  }

  private getConfidenceClass(confidence: number): string {
    if (confidence >= 0.85) return 'high';
    if (confidence >= 0.7) return 'medium';
    return 'low';
  }

  private getDefaultCSS(theme: 'light' | 'dark' | 'corporate'): string {
    const colors = theme === 'dark' ? {
      bg: '#1a1a2e',
      text: '#eee',
      headerBg: '#16213e',
      border: '#333',
      link: '#4da6ff',
      codeBg: '#0f0f23',
    } : theme === 'corporate' ? {
      bg: '#fff',
      text: '#333',
      headerBg: '#003366',
      border: '#ccc',
      link: '#0066cc',
      codeBg: '#f5f5f5',
    } : {
      bg: '#fff',
      text: '#333',
      headerBg: '#f8f9fa',
      border: '#e9ecef',
      link: '#007bff',
      codeBg: '#f6f8fa',
    };

    return `
      * { box-sizing: border-box; }
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
        line-height: 1.6;
        color: ${colors.text};
        background: ${colors.bg};
        margin: 0;
        padding: 0;
      }
      .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 2rem;
      }
      .document-header {
        background: ${colors.headerBg};
        padding: 2rem;
        margin: -2rem -2rem 2rem;
        border-bottom: 1px solid ${colors.border};
      }
      .document-header h1 {
        margin: 0 0 1rem;
        ${theme === 'corporate' || theme === 'dark' ? 'color: #fff;' : ''}
      }
      .logo { max-height: 50px; margin-bottom: 1rem; }
      .metadata { display: flex; gap: 1rem; flex-wrap: wrap; }
      .badge {
        display: inline-block;
        padding: 0.25rem 0.75rem;
        background: ${colors.codeBg};
        border-radius: 4px;
        font-size: 0.85rem;
        ${theme === 'corporate' || theme === 'dark' ? 'color: #ddd;' : ''}
      }
      .table-of-contents {
        background: ${colors.codeBg};
        padding: 1.5rem;
        border-radius: 8px;
        margin-bottom: 2rem;
      }
      .table-of-contents h2 {
        margin-top: 0;
        font-size: 1.25rem;
      }
      .table-of-contents ul {
        margin: 0;
        padding-left: 1.5rem;
      }
      .table-of-contents li {
        margin: 0.25rem 0;
      }
      .document-section {
        margin-bottom: 2rem;
        padding-bottom: 1rem;
        border-bottom: 1px solid ${colors.border};
      }
      .confidence-badge {
        font-size: 0.75rem;
        padding: 0.2rem 0.5rem;
        border-radius: 4px;
        margin-left: 0.5rem;
      }
      .confidence-badge.high { background: #d4edda; color: #155724; }
      .confidence-badge.medium { background: #fff3cd; color: #856404; }
      .confidence-badge.low { background: #f8d7da; color: #721c24; }
      table {
        width: 100%;
        border-collapse: collapse;
        margin: 1rem 0;
      }
      th, td {
        padding: 0.75rem;
        text-align: left;
        border: 1px solid ${colors.border};
      }
      th { background: ${colors.codeBg}; font-weight: 600; }
      pre {
        background: ${colors.codeBg};
        padding: 1rem;
        border-radius: 4px;
        overflow-x: auto;
      }
      code {
        font-family: 'Fira Code', Consolas, monospace;
        font-size: 0.9em;
      }
      :not(pre) > code {
        background: ${colors.codeBg};
        padding: 0.1rem 0.3rem;
        border-radius: 3px;
      }
      a { color: ${colors.link}; text-decoration: none; }
      a:hover { text-decoration: underline; }
      blockquote {
        margin: 1rem 0;
        padding-left: 1rem;
        border-left: 4px solid ${colors.border};
        color: #666;
      }
      .source-references {
        margin-top: 1rem;
        padding: 0.5rem;
        background: ${colors.codeBg};
        border-radius: 4px;
        font-size: 0.85rem;
      }
      .source-references summary {
        cursor: pointer;
        font-weight: 500;
      }
      .document-footer {
        margin-top: 3rem;
        padding-top: 1rem;
        border-top: 1px solid ${colors.border};
        text-align: center;
        font-size: 0.85rem;
        color: #666;
      }
      @media print {
        .table-of-contents { page-break-after: always; }
        .document-section { page-break-inside: avoid; }
      }
    `;
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim();
  }
}
