/**
 * Markdown Exporter
 * 
 * Exports documents to Markdown format
 */

import type { Document, DocumentSection, ExportOptions, ExportResult } from '../types.js';

export class MarkdownExporter {
  /**
   * Export document to Markdown string
   */
  export(document: Document, options?: ExportOptions): ExportResult {
    try {
      const content = this.renderDocument(document, options);
      
      return {
        success: true,
        format: 'markdown',
        content,
        size: content.length,
      };
    } catch (error) {
      return {
        success: false,
        format: 'markdown',
        error: error instanceof Error ? error.message : 'Unknown error',
      };
    }
  }

  private renderDocument(document: Document, options?: ExportOptions): string {
    const lines: string[] = [];

    // Title
    lines.push(`# ${document.title}`);
    lines.push('');

    // Metadata
    lines.push(`> Generated: ${document.generatedAt.toISOString()}`);
    lines.push(`> Version: ${document.version}`);
    lines.push(`> Confidence: ${(document.confidenceScore * 100).toFixed(1)}%`);
    lines.push('');

    // Table of Contents (if enabled)
    if (options?.includeToc !== false) {
      lines.push('## Table of Contents');
      lines.push('');
      lines.push(...this.renderTableOfContents(document.sections, options?.tocDepth || 3));
      lines.push('');
    }

    // Sections
    for (const section of document.sections) {
      lines.push(...this.renderSection(section, options));
    }

    // Footer
    lines.push('---');
    lines.push('');
    lines.push(`*This document was automatically generated by MigrationPilot.*`);
    lines.push(`*Completeness: ${(document.completeness * 100).toFixed(1)}%*`);

    return lines.join('\n');
  }

  private renderTableOfContents(
    sections: DocumentSection[],
    maxDepth: number,
    currentDepth = 1
  ): string[] {
    const lines: string[] = [];

    for (const section of sections) {
      if (section.level <= maxDepth) {
        const indent = '  '.repeat(section.level - 1);
        const anchor = this.slugify(section.title);
        lines.push(`${indent}- [${section.title}](#${anchor})`);
      }

      if (section.subsections && currentDepth < maxDepth) {
        lines.push(...this.renderTableOfContents(section.subsections, maxDepth, currentDepth + 1));
      }
    }

    return lines;
  }

  private renderSection(section: DocumentSection, options?: ExportOptions): string[] {
    const lines: string[] = [];

    // Heading
    const heading = '#'.repeat(Math.min(section.level + 1, 6));
    lines.push(`${heading} ${section.title}`);
    lines.push('');

    // Confidence indicator (if enabled and AI-generated)
    if (options?.includeConfidenceScores !== false && section.aiGenerated && section.confidence !== undefined) {
      const confidenceBadge = this.renderConfidenceBadge(section.confidence);
      lines.push(confidenceBadge);
      lines.push('');
    }

    // Content
    if (section.content) {
      lines.push(section.content);
      lines.push('');
    }

    // Source references
    if (section.sourceReferences && section.sourceReferences.length > 0) {
      lines.push('<details>');
      lines.push('<summary>Source References</summary>');
      lines.push('');
      for (const ref of section.sourceReferences) {
        if (ref.location) {
          lines.push(`- ${ref.name} (${ref.location.file}:${ref.location.startLine}-${ref.location.endLine})`);
        } else {
          lines.push(`- ${ref.name}`);
        }
      }
      lines.push('');
      lines.push('</details>');
      lines.push('');
    }

    // Subsections
    if (section.subsections) {
      for (const subsection of section.subsections) {
        lines.push(...this.renderSection(subsection, options));
      }
    }

    return lines;
  }

  private renderConfidenceBadge(confidence: number): string {
    const percentage = (confidence * 100).toFixed(0);
    let color = 'green';
    if (confidence < 0.7) color = 'red';
    else if (confidence < 0.85) color = 'yellow';

    return `![Confidence](https://img.shields.io/badge/AI_Confidence-${percentage}%25-${color})`;
  }

  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim();
  }
}
